spring.application.name=strivio

spring.config.import=optional:file:.env[.properties]

# Server port
server.port=8080

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Structural Config
# Instruct JPA/Hibernate never to modify the database schema.
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# Logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

